export enum BoardActions {
  ARCHIVE_CARD = 'ARCHIVE_CARD',
  ARCHIVE_CARD_SUCCESS = 'ARCHIVE_CARD_SUCCESS',
  COPY_CARD = 'COPY_CARD',
  MOVE_CARD = 'MOVE_CARD',
  MOVE_CARD_SIGNAL_R = 'MOVE_CARD_SIGNAL_R',
  MOVE_CARD_OTHER = 'MOVE_CARD_OTHER',
  COPY_LIST = 'COPY_LIST',
  MOVE_LIST = 'MOVE_LIST',
  MOVE_LIST_OTHER = 'MOVE_LIST_OTHER'
}
